import {
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertTriangle,
  IconAlignCenter,
  IconAlignJustified,
  IconAlignLeft,
  IconAlignRight,
  IconArrowBackUp,
  IconArrowForwardUp,
  IconArrowRight,
  IconArrowsMaximize,
  IconArrowsMinimize,
  IconBell,
  IconBlockquote,
  IconBold,
  IconBox,
  IconBrandGithub,
  IconBrandTwitter,
  IconBrandYoutube,
  IconBrightness,
  IconCalendar,
  IconCheck,
  IconChecks,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronsDown,
  IconChevronsLeft,
  IconChevronsRight,
  IconCircle,
  IconCircleCheck,
  IconCirclePlus,
  IconCircleX,
  IconClearFormatting,
  IconClipboardText,
  IconClock,
  IconCode,
  IconCodeDots,
  IconColorSwatch,
  IconColumnInsertRight,
  IconColumnRemove,
  IconCommand,
  IconCreditCard,
  IconDeviceLaptop,
  IconDots,
  IconDotsVertical,
  IconEdit,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFileText,
  IconFileTypePdf,
  IconFileTypeDoc,
  IconFileTypeXls,
  IconFileZip,
  IconFolder,
  IconGripVertical,
  IconH1,
  IconH2,
  IconH3,
  IconH4,
  IconH5,
  IconH6,
  IconHelpCircle,
  IconHighlight,
  IconIndentDecrease,
  IconIndentIncrease,
  IconInfoCircle,
  IconItalic,
  IconLayoutDashboard,
  IconLayoutKanban,
  IconLayoutSidebar,
  IconLetterCase,
  IconLine,
  IconLink,
  IconLinkOff,
  IconList,
  IconListCheck,
  IconListNumbers,
  IconLoader2,
  IconLock,
  IconLogin,
  IconLogout,
  IconMail,
  IconMessage,
  IconMinus,
  IconMoodSmile,
  IconMoon,
  IconMusic,
  IconPalette,
  IconPaperclip,
  IconPhone,
  IconPhoto,
  IconPilcrow,
  IconPizza,
  IconPlus,
  IconProps,
  IconRosetteDiscountCheck,
  IconRowInsertBottom,
  IconRowRemove,
  IconSearch,
  IconSelector,
  IconSend,
  IconSeo,
  IconSettings,
  IconShare,
  IconSlash,
  IconSparkles,
  IconStack2,
  IconStar,
  IconStrikethrough,
  IconSubscript,
  IconSun,
  IconSuperscript,
  IconTable,
  IconTableMinus,
  IconTableOff,
  IconTableColumn,
  IconTableRow,
  IconTablePlus,
  IconTextSize,
  IconTrash,
  IconTrendingDown,
  IconTrendingUp,
  IconTypography,
  IconUnderline,
  IconUpload,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconUsers,
  IconVideo,
  IconCrown,
  IconX,
  IconWorld,
  IconWorldMap,
  IconArticle,
  IconAward,
  IconQuestionMark,
  IconDeviceSim
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  // General
  alertCircle: IconAlertCircle,
  warning: IconAlertTriangle,
  arrowRight: IconArrowRight,
  check: IconCheck,
  checks: IconChecks,
  circleCheck: IconCircleCheck,
  close: IconX,
  clock: IconClock,
  code: IconCode,
  dots: IconDots,
  ellipsis: IconDotsVertical,
  externalLink: IconExternalLink,
  help: IconHelpCircle,
  info: IconInfoCircle,
  spinner: IconLoader2,
  search: IconSearch,
  settings: IconSettings,
  trash: IconTrash,
  global: IconWorld,
  worldMap: IconWorldMap,

  // Navigation / Chevrons
  chevronDown: IconChevronDown,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  chevronUp: IconChevronUp,
  chevronsDown: IconChevronsDown,
  chevronsLeft: IconChevronsLeft,
  chevronsRight: IconChevronsRight,
  chevronsUpDown: IconSelector,

  // Layout
  dashboard: IconLayoutDashboard,
  kanban: IconLayoutKanban,
  panelLeft: IconLayoutSidebar,

  // User
  user: IconUser,
  user2: IconUserCircle,
  account: IconUserCircle,
  profile: IconUser,
  employee: IconUserX,
  userPen: IconUserEdit,
  teams: IconUsers,

  // Brand
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  logo: IconCommand,

  // Communication
  chat: IconMessage,
  notification: IconBell,
  phone: IconPhone,
  video: IconVideo,
  send: IconSend,
  seo: IconSeo,
  mail: IconMail,
  paperclip: IconPaperclip,

  // Files
  page: IconFile,
  post: IconFileText,
  fileTypePdf: IconFileTypePdf,
  fileTypeDoc: IconFileTypeDoc,
  fileTypeXls: IconFileTypeXls,
  fileZip: IconFileZip,
  media: IconPhoto,
  music: IconMusic,

  // Actions
  add: IconPlus,
  edit: IconEdit,
  upload: IconUpload,
  share: IconShare,
  login: IconLogin,
  logout: IconLogout,
  gripVertical: IconGripVertical,

  // Shapes / Indicators
  circle: IconCircle,
  circleX: IconCircleX,
  plusCircle: IconCirclePlus,
  xCircle: IconCircleX,
  minus: IconMinus,

  // Theme
  sun: IconSun,
  moon: IconMoon,
  brightness: IconBrightness,
  laptop: IconDeviceLaptop,
  palette: IconPalette,

  // Commerce / Plans
  billing: IconCreditCard,
  creditCard: IconCreditCard,
  product: IconBox,
  pro: IconCrown,
  exclusive: IconStar,
  sparkles: IconSparkles,
  badgeCheck: IconRosetteDiscountCheck,
  lock: IconLock,

  // Data / Charts
  trendingDown: IconTrendingDown,
  trendingUp: IconTrendingUp,
  eye: IconEye,
  eyeOff: IconEyeOff,
  adjustments: IconAdjustmentsHorizontal,

  // Text formatting
  bold: IconBold,
  italic: IconItalic,
  underline: IconUnderline,
  strikethrough: IconStrikethrough,
  subscript: IconSubscript,
  superscript: IconSuperscript,
  highlight: IconHighlight,
  clearFormatting: IconClearFormatting,
  text: IconTypography,
  paragraph: IconPilcrow,

  // Headings
  h1: IconH1,
  h2: IconH2,
  h3: IconH3,
  h4: IconH4,

  // Lists
  bulletList: IconList,
  orderedList: IconListNumbers,
  taskList: IconListCheck,
  blockquote: IconBlockquote,

  // Alignment
  alignLeft: IconAlignLeft,
  alignCenter: IconAlignCenter,
  alignRight: IconAlignRight,
  alignJustify: IconAlignJustified,

  // Links & Media
  link: IconLink,
  unlink: IconLinkOff,
  youtube: IconBrandYoutube,
  colorSwatch: IconColorSwatch,

  // Table
  table: IconTable,
  tableOff: IconTableOff,
  tableColumn: IconTableColumn,
  tableRow: IconTableRow,

  // Code
  codeBlock: IconCodeDots,

  // Editor actions
  undo: IconArrowBackUp,
  redo: IconArrowForwardUp,
  horizontalRule: IconLine,

  // Misc
  pizza: IconPizza,
  workspace: IconFolder,
  forms: IconClipboardText,
  slash: IconSlash,
  calendar: IconCalendar,
  galleryVerticalEnd: IconStack2,
  moreHorizontal: IconDots,

  // Content
  blog: IconArticle,
  award: IconAward,
  question: IconQuestionMark,

  // Extended headings
  h5: IconH5,
  h6: IconH6,

  // Indent
  indentIncrease: IconIndentIncrease,
  indentDecrease: IconIndentDecrease,

  // Table extended
  columnInsertRight: IconColumnInsertRight,
  columnRemove: IconColumnRemove,
  rowInsertBottom: IconRowInsertBottom,
  rowRemove: IconRowRemove,
  tablePlus: IconTablePlus,
  tableMinus: IconTableMinus,

  // Font
  fontSize: IconTextSize,
  fontFamily: IconLetterCase,

  // Misc extended
  emoji: IconMoodSmile,
  maximize: IconArrowsMaximize,
  minimize: IconArrowsMinimize,

  // eSIM
  simCard: IconDeviceSim
};
